name: SpaceWarp Builder

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build the solution
        run: dotnet build "SpaceWarp.sln" -c Release

      - name: Find zip
        id: find-zip
        run: |
          echo "zip=$(ls -1 dist/SpaceWarp-*.zip | head -n 1)" >> $GITHUB_ENV
          echo "artifact_name=SpaceWarpRelease" >> $GITHUB_ENV

      - name: Upload release zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.zip }}

      - name: Find NuGet package
        id: find-nupkg
        run: |
          echo "nupkg=$(ls -1 nuget/SpaceWarp.*.nupkg | head -n 1)" >> $GITHUB_ENV
          echo "artifact_name=SpaceWarpNuGet" >> $GITHUB_ENV

      - name: Upload NuGet package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.nupkg }}
