name: SpaceWarp Builder

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Build the solution
        run: dotnet build "SpaceWarp.sln" -c ${{ matrix.run_args }}

  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      
      - name: Build the solution
        run: dotnet build "SpaceWarp.sln" -c ${{ matrix.run_args }}
        
      - name: Find Zip
        id: find-zip
        run: |
          echo "zip=$(ls -1 dist/SpaceWarp-*.zip | head -n 1)" >> $GITHUB_ENV
          echo "artifact_name=SpaceWarpRelease" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.zip }}
